### ISSUE TITLE
Extra space at end of @met attribute value

### ISSUE THREAD

**Issue by djbpitt** [bncolorado/CorpusSonetosSigloDeOro#1]
https://github.com/bncolorado/CorpusSonetosSigloDeOro/blob/2c21698e8b583e921605b9064a12f01e384e4a71/FranciscoDeMedrano/FranciscoDeMedrano_2.xml#L54

There's an extra space at the end of the "met" attribute value, which reads
```xml
met="--+-++---+- "
```
instead of
```xml
met="--+-++---+-"
```

**Comment by bncolorado** [comment]
Corrected. Thanks!!
